### ISSUE TITLE
Example of how to use this module

### ISSUE THREAD

**Issue by madsh93** [nuxt-community/partytown-module#35]
Hi Daniel

This module look awesome, and is just what I need as I have multiple third party script running on my site. I am however a bit confused as to how I actually use it with Nuxt 3.

e.g. I have this Crisp Chat module that I'd like to implement. This is the code I get from Crisp. How would I implement such script?

```js
window.$crisp = []
      window.CRISP_WEBSITE_ID = "0000"
      ;(function () {
        d = document
        s = d.createElement("script")
        s.src = "https://client.crisp.chat/l.js"
        s.async = 1
        d.getElementsByTagName("head")[0].appendChild(s)
      })()
```

**Comment by danielroe** [comment]
In your `nuxt.config`:

```ts
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  modules: ['@nuxtjs/partytown'],
  partytown: {
    forward: ['$crisp', '$crisp.push']
  },
  meta: {
    script: [
      { children: 'window.$crisp = []; window.CRISP_WEBSITE_ID = "0000"' },
      { src: 'https://client.crisp.chat/l.js', async: true, type: 'text/partytown' }
    ]
  }
})
```

Or similarly in your component/app.vue, you can call useMeta:

```vue
<script setup>
useMeta({
  script: [
    { children: `window.$crisp = []; window.CRISP_WEBSITE_ID = "0000"` },
    { src: 'https://client.crisp.chat/l.js', async: true, type: 'text/partytown' }
  ]
}}
</script>
```

**Comment by Intevel** [comment]
Should we add examples to the documentation? @danielroe

**Comment by danielroe** [comment]
@Intevel Great idea!

**Comment by Intevel** [comment]
Do you want to do this? Or should I make a PR for that?

**Comment by danielroe** [comment]
I would welcome it 😊

**Comment by Intevel** [comment]
Should I add the examples to the readme or create docs for this module?

**Comment by danielroe** [comment]
I would suggest the readme for now, and linking back to the partytown docs where possible. They will have examples for common services, for example.
