### ISSUE TITLE
Nuxt 2 + Bridge "Cannot read property 'publicAssets' of undefined"

### ISSUE THREAD

**Issue by avinean** [nuxt-community/partytown-module#60]
I got an error while running partytown on Nuxt 2 (with Bridge)
What I missed?

Package.json

{
"name": "test",
"version": "1.0.0",
"private": true,
"scripts": {
"dev": "nuxi dev",
"build": "nuxi build",
"start": "nuxi preview"
},
"dependencies": {
"@nuxtjs/partytown": "^1.1.1",
"core-js": "^3.19.3",
"nuxt-edge": "latest",
"vue": "^2.6.14",
"vue-server-renderer": "^2.6.14",
"vue-template-compiler": "^2.6.14",
"webpack": "^4.46.0"
},
"devDependencies": {
"@nuxt/bridge": "npm:@nuxt/bridge-edge"
}
}

nuxt.config.js
import { defineNuxtConfig } from "@nuxt/bridge";
import PartyTownModule from "@nuxtjs/partytown";

export default defineNuxtConfig({
// Global page headers: https://go.nuxtjs.dev/config-head
head: {
title: "test",
htmlAttrs: {
lang: "en",
},
meta: [
{ charset: "utf-8" },
{ name: "viewport", content: "width=device-width, initial-scale=1" },
{ hid: "description", name: "description", content: "" },
{ name: "format-detection", content: "telephone=no" },
],
link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }],
},

// Global CSS: https://go.nuxtjs.dev/config-css
css: [],

// Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
plugins: [],

// Auto import components: https://go.nuxtjs.dev/config-components
components: true,

// Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
buildModules: [],

// Modules: https://go.nuxtjs.dev/config-modules
modules: [PartyTownModule],
meta: {
script: [{ src: "/test-script.js", type: "text/partytown" }],
},
// partytown: {
// //
// },

// Build Configuration: https://go.nuxtjs.dev/config-build
build: {},
});

![image](https://user-images.githubusercontent.com/22274408/164019178-d4371700-ab2e-42a7-8f46-f43fd2fdf805.png)

**Comment by danielroe** [comment]
This should be resolved by upgrading your nuxt3 version with either `npx nuxi upgrade` or `yarn upgrade nuxt3` or `npm up nuxt3`. Apologies for the breaking change via minor version. Let me know if that doesn't resolve it.

**Comment by avinean** [comment]
> This should be resolved by upgrading your `@nuxt/bridge` version with either `yarn upgrade @nuxt/bridge` or `npm up @nuxt/bridge`. Apologies for the breaking change via patch version. Let me know if that doesn't resolve it.

Doesn't help.
Could you please provide a repo with workable example

**Comment by liam-p-fostr** [comment]
This error occurs because the module is trying to access the `nitro` object in your Nuxt config file but it is missing. Manually adding `nitro: {}` to the Nuxt config file resolved the above error for me, however I am having other problems in the meantime trying to get the Bridge working!

**Comment by danielroe** [comment]
Thanks @liam-p-fostr -> https://github.com/nuxt-community/partytown-module/commit/73b14fe38de1a791abb69bc3c5424cf02852286f
