### ISSUE TITLE
Crisp Chat not showing up

### ISSUE THREAD

**Issue by BlurwareAdmin** [nuxt-community/partytown-module#66]
Hi, 

Thanks for the work on this plugin. I am trying to integrate Crisp with my Nuxt3 site. Below is my nuxt.config.ts file. I followed the instructions from the README but I am still running into issues. I have a question out with the Crisp team for help as well. 

Does Nuxt not do well with third-party chat apps?  Almost everything I've tried has not worked.  Any help would be appreciated, I'm not even sure where to look for troubleshooting. 

![Screenshot Capture - 2022-04-27 - 20-53-53](https://user-images.githubusercontent.com/104033609/165655228-524ac8d8-93b7-4a01-9012-758a7c6f4eec.png)

**Comment by danielroe** [comment]
This is likely because of a change in nuxt itself from `meta` to `app.head` in defining any metadata in nuxt.config.

I'm updating the docs - thanks for the ping! Let me know if that doesn't resolve things for you...
